---
kind: pipeline
type: docker
steps:
  - name: install_dependencies
    image: node:latest
    commands:
      - cd Account\ Planning/Web
      - npm install
  - name: build_project
    image: node:latest
    commands:
      - cd Account\ Planning/Web
      - npm run build
